describe(":French called consecutively", function()
    it("reuses the same window", function()
        vim.cmd("French")
        local win = vim.api.nvim_get_current_win()
        vim.cmd("French")
        assert.are.equal(win, vim.api.nvim_get_current_win())
    end)

    it("does not close other windows", function()
        vim.cmd("split")
        local wins_before = #vim.api.nvim_list_wins()
        vim.cmd("French")
        vim.cmd("French")
        assert.are.equal(wins_before, #vim.api.nvim_list_wins())
    end)

    after_each(function()
        vim.cmd("only")
    end)
end)
